In [4]:
import requests
import datetime
import pandas as pd
import numpy as np
import config as cfg

schema="gans"
host=cfg.DATABASE_HOST
user=cfg.DATABASE_USER
password=cfg.DATABASE_PASSWORD
port=cfg.DATABASE_PORT
con = f'mysql+pymysql://{user}:{password}@{host}:{port}/{schema}'

#airports= pd.read_sql('airports',con=con)

flights = pd.DataFrame(columns=['icao','date','hours_interval','num_of_arriv','num_of_depart'])

air=['LPPR']

for a_icao in air:# airpotrs['icao']:
    n_arr = 0
    n_dep = 0
    date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d') 
    t1=['00:00','03:00','06:00','09:00','12:00','15:00','18:00','21:00']
    t2=['02:59','05:59','08:59','11:59','14:59','17:59','20:59','23:59']
    
    headers = {
        "X-RapidAPI-Host": "aerodatabox.p.rapidapi.com",
        "X-RapidAPI-Key": cfg.RAPIDAPI_KEY
    }
    
    for i in range(8):
        url = f"https://aerodatabox.p.rapidapi.com/flights/airports/icao/{a_icao}/{date}T{t1[i]}/{date}T{t2[i]}"
        
        response = requests.request("GET", url, headers=headers)
        print('Status code',response.status_code)
        if response.status_code==200:
            flights_js = response.json()
            n_arr = len(flights_js['arrivals'])
            n_dep = len(flights_js['departures'])
        else:
            n_arr = np.nan
            n_dep = np.nan
    
    flights = flights.append({'icao':a_icao,
                    'date':date,
                    'hours_interval':f"{t1}+' - '+{t2}",
                    'num_of_arriv':n_arr,
                    'num_of_depart':n_dep
                    }
                    ,ignore_index=True)
        
#flights.to_sql('flights', 
#                if_exists='append', 
#                con=con, 
#                index=False)

Status code 200
Status code 200

/var/folders/vb/vnq70sgj17jbf31jc5zsrpmc0000gn/T/ipykernel_48344/389713533.py:45: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  flights = flights.append({'icao':a_icao,

In [ ]:
flights_js['arrivals']

In [84]:
from datetime import datetime
[date,time_]=(flights_js['arrivals'][136]['movement']['scheduledTimeLocal']).split()
[time_,summerdelta]= time_.split('+')
time_=datetime.strptime(time_,'%H:%M').time()

22:30:00

In [35]:
for i in range(len(flights_js['arrivals'])):
    arrivals_scheduledTimeLocal_series = flights_js['arrivals'][i]['movement']['scheduledTimeLocal']

In [3]:
import requests
import datetime
import pandas as pd
import numpy as np
import config as cfg


schema="gans"
host=cfg.DATABASE_HOST
user=cfg.DATABASE_USER
password=cfg.DATABASE_PASSWORD
port=cfg.DATABASE_PORT
con = f'mysql+pymysql://{user}:{password}@{host}:{port}/{schema}'

flights = pd.read_sql('flights',con=con)

flights

   flights_id  icao        date  num_of_arriv  num_of_depart
0           1  LPPR  2022-06-17           210            208

In [1]:
import requests
from datetime import datetime
import pandas as pd
import numpy as np
import config as cfg


flights = pd.DataFrame(columns=['icao','date','num_of_arriv','num_of_depart'])

air=['LPPR']

for a_icao in air:# airpotrs['icao']:
    n_arr = 0
    n_dep = 0
    date = (datetime.date.today() + datetime.timedelta(days=1)).strftime('%Y-%m-%d') 
    t1=['00:00','12:00']
    t2=['11:59','23:59']
    
    headers = {
        "X-RapidAPI-Host": "aerodatabox.p.rapidapi.com",
        "X-RapidAPI-Key": cfg.RAPIDAPI_KEY
    }
    
    flight_js = list()
    
    for i in range(2):
        url = f"https://aerodatabox.p.rapidapi.com/flights/airports/icao/{a_icao}/{date}T{t1[i]}/{date}T{t2[i]}"
        
        response = requests.request("GET", url, headers=headers)
        print('Status code',response.status_code)
        if response.status_code==200:

            temp_flight_js = response.json()
            flight_js.append(temp_flight_js)

 #           if tempFlight_js == False:
#                tempFlight_js[i] = flights_js
#                tempFlight_js.update(flights_js)

#            n_arr = n_arr + len(flights_js['arrivals'])
#           n_dep = n_dep + len(flights_js['departures'])

        else:
            n_arr = np.nan
            n_dep = np.nan
    


    flights = flights.append({'icao':a_icao,
                    'date':date,
                    'num_of_arriv':n_arr,
                    'num_of_depart':n_dep
                    }
                    ,ignore_index=True)
            
#    flights.to_sql('flights', 
#                   if_exists='append', 
#                   con=con, 
#                   index=False)

Status code 200
Status code 200

/var/folders/vb/vnq70sgj17jbf31jc5zsrpmc0000gn/T/ipykernel_57016/2949820067.py:49: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  flights = flights.append({'icao':a_icao,

In [112]:
import requests
from datetime import datetime
import pandas as pd
import numpy as np
import config as cfg

In [48]:
def getTime_arrivals(i_list, i_json_a):
    [date,time_a]=(flight_js[i_list]['arrivals'][i_json_a]['movement']['scheduledTimeLocal']).split()
    [time_a,summerdelta]= time_a.split('+')
    time_a=datetime.strptime(time_a,'%H:%M').time()
    return time_a

def getTime_departures(i_list, i_json_d):
    [date,time_d]=(flight_js[i_list]['departures'][i_json_d]['movement']['scheduledTimeLocal']).split()
    [time_d,summerdelta]= time_d.split('+')
    time_d=datetime.strptime(time_d,'%H:%M').time()
    return time_d

In [51]:
a_times_series = []; d_times_series = []
for i_list in range(len(flight_js)):
    for i_json_a,i_json_d in zip((range(len(flight_js[i_list]['arrivals']))),(range(len(flight_js[i_list]['departures'])))):
        a_times_series.append(getTime_arrivals(i_list, i_json_a))
        d_times_series.append(getTime_departures(i_list, i_json_d))

In [ ]:
def getTrafficPerHour(listOfFlights):
    arrivalsPerHour = [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
    for i in range(len(listOfFlights)):
        match a_times_series[i].hour:
            case 0:
                arrivalsPerHour[0] += 1
            case 1:
                arrivalsPerHour[1] += 1
            case 2:
                arrivalsPerHour[2] += 1
            case 3:
                arrivalsPerHour[3] += 1
            case 4:
                arrivalsPerHour[4] += 1
            case 5:
                arrivalsPerHour[5] += 1
            case 6:
                arrivalsPerHour[6] += 1
            case 7:
                arrivalsPerHour[7] += 1
            case 8:
                arrivalsPerHour[8] += 1
            case 9:
                arrivalsPerHour[9] += 1
            case 10:
                arrivalsPerHour[10] += 1
            case 11:
                arrivalsPerHour[11] += 1
            case 12:
                arrivalsPerHour[12] += 1
            case 13:
                arrivalsPerHour[13] += 1
            case 14:
                arrivalsPerHour[14] += 1
            case 15:
                arrivalsPerHour[15] += 1
            case 16:
                arrivalsPerHour[16] += 1
            case 17:
                arrivalsPerHour[17] += 1
            case 18:
                arrivalsPerHour[18] += 1
            case 19:
                arrivalsPerHour[19] += 1
            case 20:
                arrivalsPerHour[20] += 1
            case 21:
                arrivalsPerHour[21] += 1
            case 22:
                arrivalsPerHour[22] += 1
            case 23:
                arrivalsPerHour[23] += 1
            case _:
                print("Didn't match a case")
    return arrivalsPerHour

a_s= getTrafficPerHour(a_times_series)

In [126]:
def getTrafficPerHour(listOfFlights):
    arrivalsPerHour = [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
    for i in range(len(listOfFlights)):
        match d_times_series[i].hour:
            case 0:
                arrivalsPerHour[0] += 1
            case 1:
                arrivalsPerHour[1] += 1
            case 2:
                arrivalsPerHour[2] += 1
            case 3:
                arrivalsPerHour[3] += 1
            case 4:
                arrivalsPerHour[4] += 1
            case 5:
                arrivalsPerHour[5] += 1
            case 6:
                arrivalsPerHour[6] += 1
            case 7:
                arrivalsPerHour[7] += 1
            case 8:
                arrivalsPerHour[8] += 1
            case 9:
                arrivalsPerHour[9] += 1
            case 10:
                arrivalsPerHour[10] += 1
            case 11:
                arrivalsPerHour[11] += 1
            case 12:
                arrivalsPerHour[12] += 1
            case 13:
                arrivalsPerHour[13] += 1
            case 14:
                arrivalsPerHour[14] += 1
            case 15:
                arrivalsPerHour[15] += 1
            case 16:
                arrivalsPerHour[16] += 1
            case 17:
                arrivalsPerHour[17] += 1
            case 18:
                arrivalsPerHour[18] += 1
            case 19:
                arrivalsPerHour[19] += 1
            case 20:
                arrivalsPerHour[20] += 1
            case 21:
                arrivalsPerHour[21] += 1
            case 22:
                arrivalsPerHour[22] += 1
            case 23:
                arrivalsPerHour[23] += 1
            case _:
                print("Didn't match a case")
    return arrivalsPerHour

d_s= getTrafficPerHour(d_times_series)

In [127]:
d_s

[0,
 0,
 0,
 0,
 0,
 2,
 26,
 6,
 10,
 7,
 7,
 14,
 19,
 10,
 15,
 5,
 15,
 6,
 11,
 14,
 9,
 5,
 2,
 0]

In [113]:
arrivals_series=[]
for i,a_i in zip((range(len(a_times_series))),(len(((getTrafficPerHour(a_times_series)))))): 
    arrivals_series.append(getTrafficPerHour(listOfFlights))

TypeError: 'int' object is not iterable

In [111]:
print(as_)

Series([], dtype: float64)

In [106]:
print(arrivals_series)

None

In [65]:
for i in range(len(a_times_series)):
    print(a_times_series[i].hour)

0
0
0
0
0
0
7
7
7
7
7
7
7
7
7
7
7
8
8
8
8
8
7
8
8
8
8
8
8
8
9
9
9
9
9
9
9
10
9
9
10
10
10
10
10
10
10
10
10
10
10
10
10
10
10
11
11
11
11
11
11
11
11
11
11
11
11
11
11
11
11
11
12
12
12
12
12
12
12
12
12
12
12
13
13
13
13
13
13
13
13
13
13
13
13
13
14
14
13
14
15
15
15
15
15
15
15
15
15
15
15
15
15
14
15
15
15
15
15
16
16
16
16
16
16
16
17
17
17
17
17
17
17
17
17
17
17
17
17
17
18
18
18
18
18
18
18
18
18
18
18
18
18
18
18
18
19
19
19
19
19
19
19
20
20
20
20
20
20
20
20
21
21
22
22
22
22
23
23
23
23
23
23

xxxxxxxxxxxxxxxxxxxxxxxxxx

In [ ]:
def getTime(i_list, i_json):
    [date,time_]=(flight_js[i_list]['arrivals'][i_json]['movement']['scheduledTimeLocal']).split()
    [time_,summerdelta]= time_.split('+')
    time_=datetime.strptime(time_,'%H:%M').time()
    return time_

In [36]:
times_series = []
for i_list in range(len(flight_js)):
    for i_json in range(len(flight_js[i_list]['arrivals'])):
        times_series.append(getTime(i_list, i_json))

In [37]:
t0,t1,t2,t3,t4,t5,t6,t7,t8,t9,t10,t11,t12,t13,t14,t15,t16,t17,t18,t19,t20,t21,t22,t23 = 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0


for i in range(len(times_series)):
    match times_series[i].hour:
        case 0:
            t0 += 1
        case 1:
            t1 += 1
        case 2:
            t2 =+ 1
        case 3:
            t3 += 1
        case 4:
            t4 += 1
        case 5:
            t5 += 1
        case 6:
            t6 += 1
        case 7:
            t7 += 1
        case 8:
            t8 += 1
        case 9:
            t9 += 1
        case 10:
            t10 += 1
        case 11:
            t11 += 1
        case 12:
            t12 += 1
        case 13:
            t13 += 1
        case 14:
            t14 += 1
        case 15:
            t15 += 1
        case 16:
            t16 += 1
        case 17:
            t17 += 1
        case 18:
            t18 += 1
        case 19:
            t19 += 1
        case 20:
            t20 += 1
        case 21:
            t21 += 1
        case 22:
            t22 += 1
        case 23:
            t23 += 1
        case _:
            print("Didn't match a case")

In [41]:
t0

6

xxxxxxxxxxxx

In [ ]:
times_series = []
range_0_to_3 = 0    ; range_3_to_6 = 0      ; range_6_to_9 = 0      ; range_9_to_12 = 0
range_12_to_15 = 0  ; range_15_to_18 = 0    ; range_18_to_21 = 0    ; range_21_to_24 = 0

for i_list in range(len(flight_js)):
    for i_json in range(len(flight_js[i_list]['arrivals'])):
        times_series.append(getTime(i_list, i_json))
        for time in time_.hour:
            #Morning Flights:
            if time < 3: 
                range_0_to_3    = range_0_to_3 + 1
            if time < 6:
                range_3_to_6    = range_3_to_6 + 1
            if time < 9: 
                range_6_to_9    = range_6_to_9 + 1
            if time < 12:
                range_9_to_12   = range_9_to_12 + 1
            #Afternoon Flights:
            if time < 15: 
                range_12_to_15  = range_12_to_15 + 1
            if time < 18:
                range_15_to_18  = range_15_to_18 + 1
            if time < 21: 
                range_18_to_21  = range_18_to_21 + 1
            else:
                range_21_to_24  = range_21_to_24 + 1

In [15]:
type(times_series)

list

In [ ]:
df2 = times_series.iloc[([0] >= '2020-09-20') & ([0] <'2021-11-08')]

In [19]:
for i in range(len(times_series)):
    print(times_series[i])

00:30:00
00:30:00
00:45:00
00:30:00
00:45:00
00:30:00
07:55:00
07:00:00
07:25:00
07:35:00
07:40:00
07:35:00
07:55:00
07:30:00
07:55:00
07:00:00
07:25:00
08:25:00
08:35:00
08:20:00
08:10:00
08:15:00
07:00:00
08:50:00
08:25:00
08:05:00
08:10:00
08:05:00
08:35:00
08:00:00
09:30:00
09:35:00
09:10:00
09:25:00
09:00:00
09:45:00
09:50:00
10:40:00
09:50:00
09:40:00
10:50:00
10:00:00
10:55:00
10:10:00
10:55:00
10:45:00
10:40:00
10:20:00
10:00:00
10:20:00
10:40:00
10:30:00
10:00:00
10:50:00
10:45:00
11:50:00
11:15:00
11:30:00
11:35:00
11:20:00
11:45:00
11:50:00
11:45:00
11:15:00
11:15:00
11:05:00
11:15:00
11:50:00
11:30:00
11:55:00
11:15:00
11:40:00
12:45:00
12:10:00
12:05:00
12:10:00
12:00:00
12:15:00
12:55:00
12:45:00
12:10:00
12:05:00
12:55:00
13:40:00
13:25:00
13:00:00
13:35:00
13:00:00
13:00:00
13:00:00
13:35:00
13:10:00
13:00:00
13:35:00
13:05:00
13:00:00
14:25:00
14:15:00
13:40:00
14:25:00
15:25:00
15:30:00
15:15:00
15:15:00
15:50:00
15:15:00
15:40:00
15:55:00
15:40:00
15:25:00
15:25:00
15:10:00
15:00:00
14:25:00
15:25:00
15:25:00
15:15:00
15:10:00
15:25:00
16:25:00
16:55:00
16:20:00
16:55:00
16:00:00
16:40:00
16:45:00
17:00:00
17:20:00
17:45:00
17:25:00
17:00:00
17:40:00
17:00:00
17:00:00
17:00:00
17:10:00
17:20:00
17:45:00
17:25:00
17:00:00
18:50:00
18:45:00
18:40:00
18:25:00
18:45:00
18:15:00
18:25:00
18:50:00
18:55:00
18:25:00
18:50:00
18:50:00
18:30:00
18:45:00
18:45:00
18:40:00
19:00:00
19:55:00
19:15:00
19:05:00
19:10:00
19:05:00
19:15:00
20:25:00
20:00:00
20:55:00
20:25:00
20:30:00
20:30:00
20:55:00
20:50:00
21:25:00
21:45:00
22:45:00
22:35:00
22:30:00
22:45:00
23:20:00
23:00:00
23:00:00
23:25:00
23:25:00
23:55:00
23:05:00
23:25:00
23:35:00
23:45:00
23:10:00
23:40:00
23:20:00
23:20:00
23:40:00
23:00:00
23:00:00
23:25:00
22:25:00
22:30:00
22:45:00
22:30:00
22:45:00
22:10:00
22:15:00
22:45:00
22:45:00
22:30:00
21:10:00
22:30:00

In [ ]:
for i in range(len(flights_js['arrivals'])):
    arrivals_scheduledTimeLocal_series = flights_js['arrivals'][i]['movement']['scheduledTimeLocal']

In [17]:
len(flight_js[1]['arrivals'])

135

In [18]:
len(flight_js)

2

In [19]:
time_series=list()
for i in range(len(flight_js)):
    for i_json in range(len(flight_js[i]['arrivals'])):
        [date,time_]=(flight_js[0]['arrivals'][i]['movement']['scheduledTimeLocal']).split()
        [time_,summerdelta]= time_.split('+')
        time_=datetime.strptime(time_,'%H:%M').time()

AttributeError: module 'datetime' has no attribute 'strptime'